// File generated by FlutterFire CLI / Smart Ranch multiplatform setup.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aFR2W6KRQoMYNaKkfbn4ourvW314XAI',
    appId: '1:1003444005118:web:b125e9854ad93006a59a72',
    messagingSenderId: '1003444005118',
    projectId: 'smartranch-innova',
    authDomain: 'smartranch-innova.firebaseapp.com',
    storageBucket: 'smartranch-innova.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9aFR2W6KRQoMYNaKkfbn4ourvW314XAI',
    appId: '1:1003444005118:android:55a9b7dc2a75ec82a59a72',
    messagingSenderId: '1003444005118',
    projectId: 'smartranch-innova',
    storageBucket: 'smartranch-innova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9aFR2W6KRQoMYNaKkfbn4ourvW314XAI',
    appId: '1:1003444005118:ios:55a9b7dc2a75ec82a59a72',
    messagingSenderId: '1003444005118',
    projectId: 'smartranch-innova',
    storageBucket: 'smartranch-innova.firebasestorage.app',
    iosBundleId: 'com.example.smartRanch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9aFR2W6KRQoMYNaKkfbn4ourvW314XAI',
    appId: '1:1003444005118:ios:55a9b7dc2a75ec82a59a72',
    messagingSenderId: '1003444005118',
    projectId: 'smartranch-innova',
    storageBucket: 'smartranch-innova.firebasestorage.app',
    iosBundleId: 'com.example.smartRanch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9aFR2W6KRQoMYNaKkfbn4ourvW314XAI',
    appId: '1:1003444005118:web:b125e9854ad93006a59a72',
    messagingSenderId: '1003444005118',
    projectId: 'smartranch-innova',
    authDomain: 'smartranch-innova.firebaseapp.com',
    storageBucket: 'smartranch-innova.firebasestorage.app',
  );
}
