apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smart_ranch
      defaultBucket: telemetry
    secureJsonData:
      token: smart-ranch-dev-token
    isDefault: true

  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: ranch_admin
    jsonData:
      database: smart_ranch
      sslmode: disable
    secureJsonData:
      password: smartranch2026
